# Generated by Django 5.1.3 on 2024-12-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
    ]
