# Generated by Django 5.1.3 on 2024-12-21 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_patientexamination_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='30 days', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='end_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(default='Once a day', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.CharField(default='No special instructions', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
