# Generated by Django 5.1.3 on 2024-12-22 10:43

import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_appointment_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.AddField(
            model_name='examination',
            name='doctor_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='examination_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientexamination',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_date',
            field=models.DateField(default=office.models.default_end_date),
        ),
    ]
