# Generated by Django 5.1.3 on 2024-12-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('General Checkup', 'General Checkup'), ('Consultation', 'Consultation'), ('Emergency', 'Emergency'), ('Follow-up', 'Follow-up')], default='General Checkup', max_length=100),
        ),
    ]
