# Generated by Django 5.1.3 on 2024-12-22 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_patient_address_patient_alcohol_patient_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examination',
        ),
        migrations.DeleteModel(
            name='PatientExamination',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
