# Generated by Django 5.1.3 on 2024-12-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_remove_appointment_doctor_remove_examination_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='No notes provided'),
        ),
    ]
