# Generated by Django 5.1.3 on 2024-12-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0018_appointment_doctor_alter_appointment_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
