# Generated by Django 5.1.3 on 2024-12-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0023_doctoravailability_delete_doctorunavailabledays'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
