# Generated by Django 5.1.3 on 2024-12-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0027_doctoravailability_delete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
