# Generated by Django 5.1.3 on 2024-12-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0028_user_google_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
